name: sealed_class
description: >
  Annotation needed to create a sealed hierarchy in Dart.
  This library is the runtime dependency.
version: 1.0.0
author: Tim Rijckaert <tim.rijckaert@gmail.com>
homepage: https://github.com/vrtdev/sealed_class_generator
repository: https://github.com/vrtdev/sealed_class_generator
issue_tracker: https://github.com/vrtdev/sealed_class_generator/issues

environment:
  sdk: ">=2.5.0 <3.0.0"

dev_dependencies:
  test: ^1.9.3