name: sealed_class
description: Make a sealed class hierarchy
version: 1.0.0
author: Tim Rijckaert <tim.rijckaert@gmail.com>

environment:
  sdk: ">=2.6.0-dev.0.0.flutter-1103600280 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.9.3