name: sealed_class
description: Make a sealed class hierarchy
version: 2.0.0
homepage: https://github.com/vrtdev/sealed_class_generator
repository: https://github.com/vrtdev/sealed_class_generator
issue_tracker: https://github.com/vrtdev/sealed_class_generator/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test: ^1.9.3