targets:
  $default:
    builders:
      sealed_class_generator|sealed_class:
        enabled: true

builders:
  sealed_class:
    target: ":sealed_class_generator"
    import: "package:sealed_class_generator/sealed_class_generator.dart"
    builder_factories: ["sealedClassBuilder"]
    build_extensions: {".dart": [".sealed_class.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]